---
- name: Close a change request
  hosts: all
  gather_facts: false
  connection: local

  vars:
    servicenow_cr: CR_Close_MM
    close_code: "successful"
    close_notes: "Change Request closed after successful remediation via Mattermost notification."

  roles:
    - snow_change_request
  run_once: true


